### PR TITLE
Excludes old asm from jsonpath

### PR DESCRIPTION
**Pull request by bono007**
See gh-34 for motivation

Fixes gh-34

### CODE REVIEW

**Comment by bono007** [comment]
@marcingrzejszczak I am not sure exactly how the branching process works in the project and there was not already  a `1.0x` branch available so I went ahead and submitted to master. If you want me to submit against that, just create the branch and I will.

**Comment by marcingrzejszczak** [comment]
Hey @bono007 ! I'm trying to figure out if this approach wouldn't be better - https://github.com/marcingrzejszczak/jsonassert/pull/36 - wdyt?

**Comment by bono007** [comment]
@marcingrzejszczak I do like that approach. Shading has saved me on more than one occasions. I was not sure how you felt about shading - I should have asked. It can be a "controversial" topic to some. I am a fan as this allows everything downstream in jsonpath to do what it does and have what it needs to do so - "we don't care what you do just don't force it upon us". I left a few comments in #36. Thanks

Also, good to see the Gradle upgrade as well. That should go in regardless of if you decide to shade or not.

**Comment by marcingrzejszczak** [comment]
Hey @bono007 I'm wondering if we should exclude the asm anyways here in jsonassert. Come to think of it `asm` is part of jayway's library that we're using directly. We're excluding it cause Spring Cloud Contract has an issue with the dependencies. That's why we should do the exclusion there in SC-Contract not here. There are users that are not using Spring and use this library. WDYT?

**Comment by bono007** [comment]
Yeh that was my initial concern of not excluding it here as it would
potentially break non-spring (non-asm) users.  Let's just go with the
exclusion in SCC.

**Comment by marcingrzejszczak** [comment]
We're deciding not to exclude the asm library here. Closing the PR.

**Pull request closed without merging**
